### ISSUE TITLE
Having trouble download from particular page

### ISSUE THREAD

**Issue by ChenQTYF** [tzoug/ThingiZIP#2]
I run ThingiZIP on chrome. It's a great.
But I'm having trouble downloading from [60 D&D Heroes - Starter Collection](https://www.thingiverse.com/thing:5651394/files). 
Could you please take a look?

**Comment by tzoug** [comment]
Hi, I tried with the link that you sent. It works for me but it takes a while because the files are quite large.

There's 60 files that are ~40mb each and 60 images.
In total, it's a few gigabytes, that's why it takes some time.

**Comment by ChenQTYF** [comment]
Thank you for your reply.
I'll give it an other try. 
How long it takes your browser pop out download save window?
I tried few hours, but it is not working.

**Comment by tzoug** [comment]
In version 3.0, download performance was improved.
You can either download it from the release page or from the chrome web store.

Since the provided link is now invalid, I can't verify if the same thing is happening with the version 3.0.
I'll be closing this comment.

If it still happends with another page, please create another issue and I will take a look.
